language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.11
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install .[flake8]
script:
  - flake8
  - ./run_tests.py
